name: Fetch latest Cardiff University data

on:
  repository_dispatch:
  # schedule:
  #   - cron:  '00 18 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest UK data
      run: |-
        mkdir -p uk/wales && cd uk/wales
        wget -q -O cardiff_university.html https://www.cardiff.ac.uk/coronavirus/covid-19-case-numbers
    - name: Commit and push UK data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: for Cardiff University ${timestamp}" || exit 0
        git push
