name: Fetch latest England data

on:
  repository_dispatch:
  schedule:
    - cron:  '26,56 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest UK data
      run: |-
        mkdir -p uk/england && cd uk/england
        for url in `wget -q https://www.england.nhs.uk/statistics/statistical-work-areas/covid-19-hospital-activity/ -O - | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 | grep uploads`; do fname=`basename $url`; wget -q -O $fname $url; done
    - name: Commit and push UK data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: for England ${timestamp}" || exit 0
        git push
