name: Fetch latest data for Northern Ireland

on:
  repository_dispatch:
  schedule:
    - cron:  '50 13 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest Northern Ireland data
      run: |-
        mkdir -p uk/northern_ireland && cd uk/northern_ireland
        wget -q -O cases_and_deaths.csv https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=N92000002&metric=newCasesByPublishDate&metric=newCasesBySpecimenDate&metric=newDailyNsoDeathsByDeathDate&metric=newOnsDeathsByRegistrationDate&format=csv
        wget -q -O testing.csv https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=N92000002&metric=newLFDTestsBySpecimenDate&metric=newPCRTestsByPublishDate&metric=newPillarOneTestsByPublishDate&metric=newPillarTwoTestsByPublishDate&metric=newTestsByPublishDate&format=csv
        wget -q -O vaccines_and_boosters.csv https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=N92000002&metric=newPeopleVaccinatedSecondDoseByPublishDate&metric=newPeopleVaccinatedThirdDoseByPublishDate&metric=newPeopleVaccinatedThirdInjectionByPublishDate&metric=newPeopleVaccinatedFirstDoseByPublishDate&metric=newPeopleVaccinatedBoosterDoseByPublishDate&format=csv
        wget -q -O admissions.csv https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=N92000002&metric=covidOccupiedMVBeds&metric=newAdmissions&metric=hospitalCases&metric=newAdmissions&format=csv
    - name: Commit and push Welsh data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: for Northern Ireland ${timestamp}" || exit 0
        git push
