name: Fetch latest Scottish data

on:
  repository_dispatch:
  schedule:
    - cron:  '27,57 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest UK data
      run: |-
        mkdir -p uk/scotland && cd uk/scotland
        for url in `wget -q https://www.gov.scot/publications/coronavirus-covid-19-trends-in-daily-data/ -O - | grep -o -E 'href="([^"#]+)"' | cut -d'"' -f2 | grep publications | grep 'xlsx$'`; do fname=`basename $url`; wget -q -O $fname https://gov.scot${url}; done
    - name: Commit and push data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: for Scottish ${timestamp}" || exit 0
        git push
