name: Fetch latest UK data

on:
  repository_dispatch:
  schedule:
    - cron:  '25,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest UK data
      run: |-
        mkdir -p tmp_uk && cd tmp_uk
        conditional-get --etags ../etags.json -v https://c19downloads.azureedge.net/downloads/data/data_latest.json
        (test -f data_latest.json && jq . data_latest.json > ../uk/data_latest.json) || echo "No update for data_latest.json, skipping."
        conditional-get --etags ../etags.json -v https://c19pub.azureedge.net/utlas.geojson
        (test -f utlas.geojson && jq . utlas.geojson > ../uk/utlas.geojson) || echo "No update for utlas.geojson, skipping."
        conditional-get --etags ../etags.json -v https://c19pub.azureedge.net/countries.geojson
        (test -f countries.geojson && jq . countries.geojson > ../uk/countries.geojson) || echo "No update for countries.geojson, skipping."
        conditional-get --etags ../etags.json -v https://c19pub.azureedge.net/regions.geojson
        (test -f regions.geojson && jq . regions.geojson > ../uk/regions.geojson) || echo "No update for regions.geojson, skipping."
        conditional-get --etags ../etags.json -v https://c19downloads.azureedge.net/downloads/json/coronavirus-cases_latest.json
        (test -f coronavirus-cases_latest.json && jq . coronavirus-cases_latest.json > ../uk/coronavirus-cases_latest.json) || echo "No update for coronavirus-cases_latest.json, skipping."
        conditional-get --etags ../etags.json -v https://c19downloads.azureedge.net/downloads/json/coronavirus-deaths_latest.json
        (test -f coronavirus-deaths_latest.json && jq . coronavirus-deaths_latest.json > ../uk/coronavirus-deaths_latest.json) || echo "No update for coronavirus-deaths_latest.json, skipping."
        cd .. && rm -rf tmp_uk
        cd uk
        wget -O r_number.html https://www.gov.uk/government/news/government-publishes-latest-r-number
        mkdir -p wales && cd wales
        conditional-get --etags ../../etags.json -v http://www2.nphs.wales.nhs.uk:8080/CommunitySurveillanceDocs.nsf/61c1e930f9121fd080256f2a004937ed/77fdb9a33544aee88025855100300cab/$FILE/Rapid%20COVID-19%20surveillance%20data.xlsx
        cd ..
        mkdir -p scotland && cd scotland
        # wget -O week_14.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-14.zip
        # wget -O week_15.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-15.zip
        # wget -O week_16.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-16.zip
        # wget -O week_17.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-17.zip
        # wget -O week_18.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-18.zip
        wget -O week_19.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-19.zip
        wget -O week_20.zip https://www.nrscotland.gov.uk/files//statistics/covid19/covid-deaths-data-week-20.zip
        cd ..
        mkdir -p northern_ireland && cd northern_ireland
        wget -O weekly_deaths_2020.xls "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/Weekly_Deaths.xls"
        wget -O historical_deaths_2009-2019.xls "https://www.nisra.gov.uk/sites/nisra.gov.uk/files/publications/Weekly_Deaths%20-%20Historical.xls"
    - name: Commit and push UK data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest UK data: ${timestamp}" || exit 0
        git push
