name: Fetch latest UK data

on:
  repository_dispatch:
  schedule:
    - cron:  '25,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest UK data
      run: |-
        mkdir -p tmp_uk && cd tmp_uk
        conditional-get --etags ../etags.json -v https://c19downloads.azureedge.net/downloads/data/data_latest.json
        jq . data_latest.json > ../uk/data_latest.json
        conditional-get --etags ../etags.json -v https://c19pub.azureedge.net/utlas.geojson
        jq . utlas.geojson > ../uk/utlas.geojson
        conditional-get --etags ../etags.json -v https://c19pub.azureedge.net/countries.geojson
        jq . countries.geojson > ../uk/countries.geojson
        conditional-get --etags ../etags.json -v https://c19pub.azureedge.net/regions.geojson
        jq . regions.geojson > ../uk/regions.geojson
        conditional-get --etags ../etags.json -v https://c19downloads.azureedge.net/downloads/json/coronavirus-cases_latest.json
        jq . coronavirus-cases_latest.json > ../uk/coronavirus-cases_latest.json
        conditional-get --etags ../etags.json -v https://c19downloads.azureedge.net/downloads/json/coronavirus-deaths_latest.json
        jq . coronavirus-deaths_latest.json > ../uk/coronavirus-deaths_latest.json
        cd .. && rm -rf tmp_uk
    - name: Commit and push UK data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest UK data: ${timestamp}" || exit 0
        git push
