name: Fetch latest UK data

on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '25,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest UK data
      run: |-
        conditional-get -v https://c19downloads.azureedge.net/downloads/data/data_latest.json
        jq . data_latest.json > data_latest.json.tmp && mv data_latest.json.tmp uk/data_latest.json
        conditional-get -v https://c19pub.azureedge.net/utlas.geojson
        jq . utlas.geojson > utlas.geojson.tmp && mv utlas.geojson.tmp uk/utlas.geojson
        conditional-get -v https://c19pub.azureedge.net/countries.geojson
        jq . countries.geojson > countries.geojson.tmp && mv countries.geojson.tmp uk/countries.geojson
        conditional-get -v https://c19pub.azureedge.net/regions.geojson
        jq . regions.geojson > regions.geojson.tmp && mv regions.geojson.tmp uk/regions.geojson
    - name: Commit and push UK data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest UK data: ${timestamp}" || exit 0
        git push
