name: Fetch latest worldwide data

on:
  repository_dispatch:
  schedule:
    - cron:  '00 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest worldwide data
      run: |-
        mkdir -p tmp_worldwide && cd tmp_worldwide
        # conditional-get --etags ../etags.json -v https://opendata.ecdc.europa.eu/covid19/casedistribution/json -o index.json
        # (test -f index.json && jq . index.json > ../worldwide/worldwide.json) || echo "No update for index.json, skipping."
        cd .. && rm -rf tmp_worldwide
        cd worldwide
        wget -q -O time_series_covid19_confirmed_global.csv https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
        wget -q -O time_series_covid19_deaths_global.csv https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
        wget -q -O time_series_covid19_recovered_global.csv https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv
        wget -q -O new_worldwide_deaths.csv https://covid.ourworldindata.org/data/ecdc/new_deaths.csv
        wget -q -O new_worldwide_covid_deaths.csv https://covid.ourworldindata.org/data/ecdc/total_deaths.csv
        echo "done"
    - name: Commit and push worldwide data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest worldwide data: ${timestamp}" || exit 0
        git push
